# Generated by Django 3.1.5 on 2021-02-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(upload_to='__MEDIA/RESUME/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.FileField(upload_to='__MEDIA/JD/'),
        ),
    ]
