# Generated by Django 3.1.5 on 2021-02-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='comments',
        ),
        migrations.AddField(
            model_name='field',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
