# Generated by Django 3.1.7 on 2021-03-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(upload_to='Resume/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requisition_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Offered', 'Offered'), ('On-Hold', 'On-Hold'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisitioncandidate',
            name='candidate_status',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('On-Hold', 'On-Hold'), ('Offered', 'Offered'), ('Joined', 'Joined'), ('In-Progress', 'In-Progress')], default='In-Progress', max_length=20),
        ),
    ]
