# Generated by Django 3.1.5 on 2021-02-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='noticePeriod',
            new_name='notice_period',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='college_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
