# Generated by Django 3.1.5 on 2021-02-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('pending', 'pending')], max_length=10),
        ),
    ]
