# Generated by Django 3.1.5 on 2021-02-10 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jd',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 9, 28, 23, 292287)),
        ),
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 9, 28, 23, 292287)),
        ),
    ]
