# Generated by Django 3.1.5 on 2021-02-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='open_to_internal',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='job',
            name='requisition_status',
            field=models.CharField(choices=[('open', 'open'), ('offered', 'offered'), ('closed', 'closed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='RequisitionCandidate',
            fields=[
                ('requisition_candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('referred_date', models.DateField(blank=True, null=True)),
                ('expected_doj', models.DateField(blank=True, null=True)),
                ('actual_doj', models.DateField(blank=True, null=True)),
                ('candidate_status', models.CharField(choices=[('selected', 'selected'), ('rejected', 'rejected'), ('on_hold', 'on_hold'), ('offered', 'offered'), ('joined', 'joined'), ('in_progress', 'in_progress')], default='in_progress', max_length=20)),
                ('candidate_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Incedoinc.candidate')),
                ('referred_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Incedoinc.employee')),
                ('requisition_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Incedoinc.job')),
            ],
        ),
    ]
