# Generated by Django 3.1.5 on 2021-02-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0002_auto_20210204_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating_cpp',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating_java',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating_python',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating_sql',
        ),
    ]
