# Generated by Django 3.1.5 on 2021-01-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0002_auto_20210126_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='raisedByEmployee',
            field=models.ManyToManyField(blank=True, related_name='Employee', to='Incedoinc.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='incedoCode',
            field=models.CharField(default=None, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='job',
            name='positionOwner',
        ),
        migrations.AddField(
            model_name='job',
            name='positionOwner',
            field=models.ManyToManyField(blank=True, related_name='owner', to='Incedoinc.Employee'),
        ),
    ]
