# Generated by Django 3.1.5 on 2021-02-09 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0002_auto_20210210_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jd',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 0, 25, 26, 290998)),
        ),
    ]
