# Generated by Django 3.1.5 on 2021-02-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0002_auto_20210206_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='comment',
            new_name='comments',
        ),
    ]
