# Generated by Django 3.1.5 on 2021-02-09 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0003_auto_20210210_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jd',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 0, 26, 54, 910841)),
        ),
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 0, 26, 54, 911838)),
        ),
    ]
