# Generated by Django 3.1.5 on 2021-02-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0003_auto_20210205_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(blank=True, choices=[('pass', 'pass'), ('fail', 'fail'), ('pending', 'pending')], max_length=10),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(blank=True, choices=[('python', 'python'), ('java', 'java'), ('c++', 'c++'), ('sql', 'sql'), ('JAVA script', 'java script'), ('cloud computing', 'cloud computing'), ('Linux', 'Linux'), ('image Processing', 'image processing'), ('C#', 'C#'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Cotlin', 'Cotlin'), ('AWS', 'AWS'), ('Neural Networks', 'Neural Networks'), ('Deep Learning', 'Deep Learning'), ('machine learning', 'machine learning'), ('.NET', '.NET')], max_length=20, null=True),
        ),
    ]
