# Generated by Django 3.1.5 on 2021-01-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0003_auto_20210126_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='positionOwner',
        ),
        migrations.AddField(
            model_name='job',
            name='positionOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_pos', to='Incedoinc.employee'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='raisedByEmployee',
        ),
        migrations.AddField(
            model_name='job',
            name='raisedByEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_emp', to='Incedoinc.employee'),
        ),
    ]
