# Generated by Django 3.1.5 on 2021-02-09 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incedoinc', '0004_auto_20210210_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jd',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 0, 49, 58, 818997)),
        ),
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 0, 49, 58, 819988)),
        ),
    ]
